### ISSUE TITLE
Front matter paragraph has different font size to rest of document

### ISSUE THREAD

**Issue by ysb33r** [gradle-guides/migrating-from-maven#1]
Discovered by @hands and is open for discussion. This is current set ans an issue against this guide as it is where it was found, but it may well be a general fix that is required

See: https://gradle.slack.com/archives/guides/p1488897984000057

**Comment by chaficnajjar** [comment]
The [CSS rule](https://github.com/gradle/guides/blob/master/asciidoctor.css#L174) responsible for setting a different font size to the introductory text of each guide is part of the default stylesheet that Asciidoctor generates.

Proof: in the `gs-template` repository, comment out [`stylesheet: null`](https://github.com/gradle-guides/gs-template/blob/master/build.gradle#L26) in build.gradle, build the template guide with `./gradlew build` and check out line 63 of `gs-template/build/html5/asciidoctor.css`

However, I can quickly override this CSS rule and set the font size of the introduction to be the same as the font size of the body, and it will get applied to all the guides.

**Comment by pioterj** [comment]
Let's do this. It looks weird especially when the first paragraph of the introduction has larger font and the second one has a smaller one like here: https://guides.gradle.org/creating-new-gradle-builds/.

**Comment by ysb33r** [comment]
This has been merged, right? Should we close this one?
