### ISSUE TITLE
Add some more practical differences

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/migrating-from-maven#2]
I think we should add some more practical differences in using Gradle compared to Maven. Examples:
- Incremental builds and not using `clean` all the time
- Using wrapper

Here's a good source of inspiration: http://blog.stack.foundation/2017/05/31/10-tips-for-migrating-from-maven-to-gradle/

@ysb33r @kousen WDYT?

**Comment by eriwen** [comment]
@pioterj Instead, I help users make a case for Gradle and link to our feature and performance comparison here: https://github.com/gradle-guides/migrating-from-maven/pull/8/files?diff=split#diff-26e5159b22409dca66bbd718ccd8cc72R9

Good?

**Comment by pioterj** [comment]
Looks good. We may want to mention the two specific points above on https://gradle.org/maven-vs-gradle/ page.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #210](https://github.com/gradle/guides/issues/210) via [**ZenHub**](https://www.zenhub.com/)
